// <auto-generated />
namespace GestionaleLibreria.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ModificaVenditaDettaglio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificaVenditaDettaglio));
        
        string IMigrationMetadata.Id
        {
            get { return "202503121440539_ModificaVenditaDettaglio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
